"""
Django settings for vidomina project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
from dotenv import load_dotenv
from pathlib import Path,  os
from os.path import join
from django.urls import reverse_lazy

#load the .env file
load_dotenv()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")
print(SECRET_KEY)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS =  ['mysite.com', 'localhost', '127.0.0.1', 'streamoneplus.com', '192.168.43.184']
SITE_ID = 1

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    #'threadedcomments',
    #'django_comments',
    'django.contrib.sites',
     'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.auth0',
    'allauth.socialaccount.providers.facebook',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.instagram',
    'allauth.socialaccount.providers.telegram',
    'allauth.socialaccount.providers.twitter',
    'allauth.socialaccount.providers.yahoo',
    'tailwind',
    'theme',
    'django_browser_reload',
    'videos',
    'homepage',
    'hitcount',
    'django_htmx',
    'django_extensions',
   
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "django_browser_reload.middleware.BrowserReloadMiddleware",
    'django_htmx.middleware.HtmxMiddleware',
    "allauth.account.middleware.AccountMiddleware",
]


#COMMENTS_APP = 'threadedcomments'

#SOCIALACCOUNT_ONLY = True

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        # For each OAuth based provider, either add a ``SocialApp``
        # (``socialaccount`` app) containing the required client
        # credentials, or list them here:
        'APP': {
            'client_id' : os.getenv("googl_client_id"),
            'secret': os.getenv("google_secret_key"),
            'key': ''
        },
        'SCOPE': [
                    'profile',
                    'email',
                 ],
        'AUTH_PARAMS':{
            'access_type': 'offline',
            },
        'OAUTH_PKCE_ENABLED':True,
        'FETCH_USERINFO' :True,
        },
     
    
    'facebook': {
        # For each OAuth based provider, either add a ``SocialApp``
        # (``socialaccount`` app) containing the required client
        # credentials, or list them here:
        'APP': {
            'client_id': os.getenv("facebook_client_id"),
            'secret': os.getenv("facebook_secret"),
            'key': ''
        }
    },
    
    'twitter': {
        # For each OAuth based provider, either add a ``SocialApp``
        # (``socialaccount`` app) containing the required client
        # credentials, or list them here:
        'APP': {
            'client_id': os.getenv("twitter_client_id"),
            'secret': os.getenv("twitter_secret"),
            'key': ''
        }
    },
}
print(f"Google:  {SOCIALACCOUNT_PROVIDERS['google']['APP']['client_id']}")
print(f"Facebook:  {SOCIALACCOUNT_PROVIDERS['facebook']['APP']['client_id']}")
print(f"Twitter:  {SOCIALACCOUNT_PROVIDERS['twitter']['APP']['client_id']}")
ACCOUNT_DEFAULT_HTTP_PROTOCOL = 'https'
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',]

ACCOUNT_EMAIL_VERIFICATION= "none"
LOGIN_REDIRECT_URL = "/"

ROOT_URLCONF = 'vidomina.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.request',
                
            
            ],
        },
    },
]

WSGI_APPLICATION = 'vidomina.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = str(join(BASE_DIR, 'staticfiles'))
STATICFILES_DIRS = (str(join(BASE_DIR, 'static')), )
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
print([os.path.join(BASE_DIR, '/static')])

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

TAILWIND_APP_NAME = 'theme'
INTERNAL_IPS = [
    "127.0.0.1",
]