from django.urls import path
from . import views
from .views import Like_comment

app_name = 'videos'
urlpatterns = [
    
    path('<int:year>/<int:month>/<int:day>/<slug:video>/',         
          views.Video_details, name='post_detail'),
    path('likes/<int:pk>/', views.video_likes, name="video-like"),
    #path('post_comment/<int:post_id>',   views.post_comment, name='post_comment'),
    path('comment/reply/', views.reply_page, name="reply"),
    path('htmx/post/<int:post_pk>/comment/<int:pk>/like',  Like_comment.as_view(), name='comment-like'),
    path('edit-comment/<int:pk>',  views.Update_Comment, name='edit-comment'),
    path('animation/', views.animation_home, name="animation"),
    path('loading/', views.all_animation_video_view, name="more-animation-video"),
    path('artistic/', views.artistic_home, name="artistic"),
    path('loading/', views.all_artistic_video_view, name="more-artistic-video"),
    path('sport/', views.sport_home, name="sport"),
    path('loading/', views.all_sport_video_view, name="more-sport-video"),
    path('comic/', views.comic_home, name="comic"),
    path('loading/', views.all_comic_video_view, name="more-comic-video"),
    path('crime/', views.crime_home, name="crime"),
    path('loading/', views.all_crime_video_view, name="more-crime-video"),
    path('discovery/', views.discovery_home, name="discovery"),
    path('loading/', views.all_discovery_video_view, name="more-discovery-video"),
    path('documentary/', views.documentary_home, name="documentary"),
    path('loading/', views.all_documentary_video_view, name="more-documentary-video"),
    path('happening/', views.happening_home, name="happening"),
    path('loading/', views.all_happening_video_view, name="more-happening-video"),
    path('howto/', views.howto_home, name="howto"),
    path('loading/', views.all_howto_video_view, name="more-howto-video"),
    path('leadership-motivation/', views.leadership_home, name="leadership"),
    path('loading/', views.all_leadership_video_view, name="more-leadership-video"),
    path('movies/', views.movies_home, name="movies"),
    path('loading/', views.all_movies_video_view, name="more-movies-video"),
    path('music/', views.music_home, name="music"),
    path('loading/', views.all_music_video_view, name="more-music-video"),
    path('people-event/', views.people_home, name="people"),
    path('loading/', views.all_people_video_view, name="more-people-video"),
    path('pet-wildLife/', views.animal_home, name="animal"),
    path('loading/', views.all_animal_video_view, name="more-animal-video"),
    path('politics-politician/', views.politics_home, name="politics"),
    path('loading/', views.all_politics_video_view, name="more-politics-video"),
    path('properties/', views.properties_home, name="properties"),
    path('loading/', views.all_properties_video_view, name="more-properties-video"),
    path('religion/', views.religion_home, name="religion"),
    path('loading/', views.all_religion_video_view, name="more-religion-video"),
    path('stem/', views.stem_home, name="stem"),
    path('loading/', views.all_stem_video_view, name="more-stem-video"),
]
